### ISSUE TITLE
Provide a stylesheet for auto code formatting

### ISSUE THREAD

**Issue by Marcarrian** [fastboyz/Qiyana-Data-aggregator#15]
**Is your feature request related to a problem? Please describe.**
When multiple people work on the project everyone should have the same code formatting.

**Describe the solution you'd like**
I would use the google stylesheet for java https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml

**Comment by Marcarrian** [comment]
@fastboyz is this okay for you?

**Comment by fastboyz** [comment]
I think its a great Idea!
